### ISSUE TITLE
Callout Blocks

### ISSUE THREAD

**Issue by dave-fink** [aemsites/ingredion#17]
Throughout the site this block appears.  We can call it "callout" with variant classes for the different styles.

1. Determine the different callout blocks and identify the default
2. Use a (variant) style for the different versions

https://www.ingredion.com/na/en-us/ingredients/ingredient-types/extracts.html
![image](https://github.com/user-attachments/assets/035be610-1383-48f1-8fdc-8a4b294dfe87)

https://www.ingredion.com/apac/en-au/be-whats-next/better-nutrition-key-to-added-value-consumers-seek.html
![image](https://github.com/user-attachments/assets/80a671c4-9c41-4ecc-ab12-b9be3903fa50)
![image](https://github.com/user-attachments/assets/4ab95b56-4af7-4324-971d-b5a15aee26c3)
![image](https://github.com/user-attachments/assets/c64b995a-352f-4326-90d3-ba120d203de7)

**Comment by varunmitra** [comment]
another variant

![Screenshot 2024-11-19 at 1 51 27 PM](https://github.com/user-attachments/assets/83970ac3-af3c-454c-a72d-0f3563168c61)

URL: https://www.ingredion.com/na/en-us/ingredients.html
