### ISSUE TITLE
Hero

### ISSUE THREAD

**Issue by dave-fink** [aemsites/ingredion#4]
Create hero block.

1. Remove auto block functionality
3. Make block configurable as there are multiple variants (below are a few, there may be others)

https://www.ingredion.com/na/en-us.html
![image](https://github.com/user-attachments/assets/7c69aa3c-8a42-4e02-ad56-097554b9390d)

https://www.ingredion.com/na/en-us/categories/animal-nutrition.html
![image](https://github.com/user-attachments/assets/53380285-2a68-4cb1-8553-aef988526187)

https://www.ingredion.com/na/en-us/news-events/news.html?activePage=1&perPage=6
![image](https://github.com/user-attachments/assets/080a8514-1426-4735-a25e-3f55fedecb01)

**Comment by ujjwal5** [comment]
Adding a couple of more variants:

https://www.ingredion.com/na/en-us/company/meet-ingredion/sustainability.html

<img width="1727" alt="Screenshot 2024-11-27 at 2 02 56 PM" src="https://github.com/user-attachments/assets/dfe7d2e9-1037-45f6-8db5-1230352d32cc">

https://www.ingredion.com/na/en-us/news-events/news/Pea-protein-improved-dispersibility-RTM-beverages.html

<img width="1726" alt="Screenshot 2024-11-27 at 2 03 09 PM" src="https://github.com/user-attachments/assets/b879da90-812f-4672-b7b6-7033634f3479">

**Comment by ujjwal5** [comment]
Another variant: Text left indented: https://www.ingredion.com/na/en-us/be-whats-next/better-nutrition-key-to-added-value-consumers-seek.html

<img width="1725" alt="Screenshot 2024-11-27 at 2 06 57 PM" src="https://github.com/user-attachments/assets/8dae91db-1892-47e5-a456-9d52a0baa193">
